services:
  gpodder:
    container_name: opodsync
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./server/data
        target: /var/www/server/data
    hostname: opodsync.localhost
    ports:
      - 8081:8081
